name: Kongsberg-MBES-data-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - alabaster=0.7.12
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.2.0
  - autopep8=1.5.4
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - black=20.8b1
  - bleach=3.2.1
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.11.8
  - cairo=1.16.0
  - certifi=2020.11.8
  - cffi=1.14.3
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - colorama=0.4.3
  - cryptography=3.2.1
  - curl=7.71.1
  - cycler=0.10.0
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - docutils=0.16
  - entrypoints=0.3
  - entwine=2.1.0
  - expat=2.2.9
  - flake8=3.8.4
  - freetype=2.10.2
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.1.2
  - geographiclib=1.50
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - glib=2.66.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - helpdev=0.7.1
  - icu=67.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - intervaltree=3.0.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9d
  - jsoncpp=1.8.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_pygments=0.1.1
  - jupyterthemes=0.20.0
  - kealib=1.4.13
  - keyring=21.5.0
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - laszip=3.4.3
  - laz-perf=1.4.4
  - lazy-object-proxy=1.4.3
  - lesscpy=0.13.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - libcurl=7.71.1
  - libffi=3.2.1
  - libgdal=3.1.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lxml=4.5.2
  - lz4-c=1.9.2
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.1
  - msys2-conda-epoch=20160418
  - mypy_extensions=0.4.3
  - nbclient=0.5.0
  - nbconvert=6.0.5
  - nbformat=5.0.7
  - nest-asyncio=1.4.0
  - nitro=2.7.dev6
  - nodejs=14.11.0
  - notebook=6.1.4
  - numpy=1.19.1
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.4
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - paramiko=2.7.2
  - parso=0.7.0
  - pathspec=0.8.1
  - pathtools=0.1.2
  - pcre=8.44
  - pdal=2.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - pixman=0.38.0
  - pluggy=0.13.1
  - ply=3.11
  - poppler=0.89.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - proj=7.1.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - psutil=5.7.3
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.1
  - pylint=2.6.0
  - pyls-black=0.4.6
  - pyls-spyder=0.1.1
  - pynacl=1.4.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.1
  - python-pdal=2.3.4
  - python_abi=3.8
  - pytz=2020.4
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qdarkstyle=2.8.1
  - qt=5.12.9
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - rasterio=1.1.7
  - regex=2020.11.13
  - requests=2.25.0
  - rope=0.18.0
  - rtree=0.9.4
  - scipy=1.5.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - snowballstemmer=2.0.0
  - snuggs=1.4.7
  - sortedcontainers=2.3.0
  - sphinx=3.3.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.2.0
  - spyder-kernels=1.10.0
  - sqlite=3.33.0
  - tbb=2020.1
  - terminado=0.9.1
  - testpath=0.4.4
  - three-merge=0.1.1
  - tiledb=2.0.8
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.0.4
  - traitlets=5.0.4
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - ujson=4.0.1
  - urllib3=1.25.11
  - vc=14.1
  - veusz=3.2.1
  - vs2015_runtime=14.16.27012
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
